version: "3"
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
         KAFKA_ADVERTISED_HOST_NAME: kafka
         KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
         KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
         KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
         KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
  mongo:
    image: mongo
    container_name: mongo
    ports:
     - '27017:27017'
    depends_on:
      - kafka
  sso:
    # build: ./sso
    # volumes:
    #   - ./sso/:/app
    image: anil8484/sso 
    container_name: sso
    ports: 
     - '3200:3200'
    external_links: 
    - mongo
    depends_on:
      - mongo

  transactions:
    # build: ./transactions
    # volumes:
    #   - ./transactions/:/app
    image: anil8484/transactions 
    container_name: transactions
    ports: 
      - '3100:3100'
    external_links: 
    - mongo
    depends_on:
      - sso
  reports:
    build: ./reports  #local
    volumes:            #local
      - ./reports/:/app    #local
    # image: anil8484/reports     #server
    # container_name: reports      #server
    ports:  
     - '3300:3300'
    depends_on:
      - sso
  nginx:
    # build: ./nginx
    image: anil8484/nginx 
    container_name: nginx
    depends_on:
      - reports
      - transactions
      - sso
    ports: 
      - '80:80'

    

